# Generated by Django 4.1.7 on 2023-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
